import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const hello = trpc.example.hello.useQuery({ text: "from tRPC" });

  if(hello.isLoading) return <div>Loading...</div>

  if(hello.data) return <div>{hello.data.greeting}</div>

  return (
    <>
      <Head>
        <title>Choose The GOAT</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-2xl font-bold tracking-tight text-white sm:text-[5rem]">
            Which Player is Better?
          </h1>
          <div className="mt-8 border rounded p-8 flex justify-between items-center max-w-2xl">
            <div className="w-16 h-16 bg-cyan-800"></div>
            <div className="p-8">Vs</div>
            <div className="w-16 h-16 bg-cyan-800"></div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
