import { type NextPage } from "next";
import { useEffect, useState} from "react";
import Head from "next/head";
import { getOptionsForVote } from "../utils/getRandomPlayer";
import { trpc } from "../utils/trpc";


const Home: NextPage = () => {
    const [ids, upateIds] = useState(getOptionsForVote());
    const [first, second] = ids;

    const firstPokemon = trpc.example.getPokemonById.useQuery({ id: first ?? 0});
    const secondPokemon = trpc.example.getPokemonById.useQuery({ id: second ?? 0});
    console.log(firstPokemon.data);
    console.log(secondPokemon.data);

    if(firstPokemon.isLoading || secondPokemon.isLoading)
    return null

  return (
    <>
      <Head>
        <title>Choose The GOAT</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-2xl font-bold tracking-tight text-white sm:text-[5rem]">
            Which Player is Better?
          </h1>
          <div className="mt-8 border rounded p-8 flex justify-between items-center max-w-2xl">
            <div className="w-64 h-64 flex flex-col">
              <img className="w-full" src={firstPokemon.data?.sprites.front_default} alt="Pokemon 1"/>
              <div className="p-2"></div>
              <div className="text-xl text-center capitalize mt-[-2rem]">{firstPokemon.data?.name}</div>
            </div>
            <div className="p-8">Vs</div>
            <div className="w-64 h-64 flex flex-col">
              <img className="w-full" src={secondPokemon.data?.sprites.front_default} alt="Pokemon 1"/>
              <div className="p-2"></div>
              <div className="text-xl text-center capitalize mt-[-2rem]">{secondPokemon.data?.name}</div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
